### ISSUE TITLE
theory/scales might be improved

### ISSUE THREAD

**Issue by youshy** [go-audio/music#1]
First of all - amazing idea with `go-audio`!

I can see a few areas of improvement though.

# Scale definition struct needs a bit of rework

```golang
// ScaleDefinition defines a scale by giving it a name and the spacing between adjacent notes on the chromatic scale.
type ScaleDefinition struct {
	// Popular indicates that the scale is commonly used
	Popular bool
	// Greek mode scale
	Greek     bool
	Name      ScaleName
	HalfSteps []int
	// InScale indicate what notes are in and which aren't
	InScale     [12]bool
	_scaleNotes []int // cache
}
```

I kinda disagree with popular boolean as music is not very `0/1`. Popularity derivates from the genre itself - best example would be jazz which uses extended modes or modes derivated from other scales other than ionian. Better implementation might be:

```golang
type ScaleDefinition struct {
  // as most of the scales have their parent mode
  // it would be useful to note the parent, not if greek or not
  isChild         bool
  ParentScale     *Scale // or any other pointer to the parent. If not child - leave empty?
  Name            ScaleName
  HalfSteps       []int // half steps are useful only if we're talking about western music theory
```

This struct is way lighter and also indicates the connections between all the modes (based on modal theory for natural, harmonic and melodic minors).

Also, that might change the way we handle the rest of the definitions. If you need any help with implementing the theory bit in Go - let me know - I'm more than happy to help!

**Comment by mattetti** [comment]
I totally agree, I started something light to do some tests and quickly found myself somewhat stuck. The challenge being how to guess the most likely scale and chords hence that awkward Boolean. Help would me more than welcome

**Comment by youshy** [comment]
I can hop in on the Scales bit and then we'll see where that leads us, how about that?

**Comment by mattetti** [comment]
Perfect, thanks a lot

**Comment by youshy** [comment]
Initial PR Ready - #2
